### PR TITLE
Add Text Filter to Learn Page

### PR DESCRIPTION
**Pull request by jestapinski**
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/search-text-box/learn)

This PR adds the new "Text Filter" feature to the learn page. This filter hits Realm to get search results based on a given query. As of now, the filter works with the following constraints:
- If the user is on the videos or podcasts tab, they should still see that content. Videos and podcasts are *not supported* by the text filter
- If the user filters using the text filter, the other filter options (products, languages) are effectively disabled. A forthcoming PR will add the ability for these to be disabled more clearly.

I'm working on a suite of cypress tests for the learn page (we do not have any at this time). Cypress tests for this feature are included there and will open that PR shortly.

### CODE REVIEW

**Review by melissarudofsky — APPROVED** [review]
Looks great! 
Unrelated to this PR but what is the search functionality? I did find it a weird experience that if I'm looking for a word like "page" and I start typing "pag", I get no results but then if I add the "e" there are results

**Comment by jestapinski** [comment]
> Looks great!
> Unrelated to this PR but what is the search functionality? I did find it a weird experience that if I'm looking for a word like "page" and I start typing "pag", I get no results but then if I add the "e" there are results

Great question! Deepak actually wrote a full-text search backend using Realm. My guess is he requires 4+ characters to give a response. I'll ask him about it.

**Comment by melissarudofsky** [comment]
> full-text

I think it only matches full words!

**Comment by jestapinski** [comment]
> > full-text
> 
> I think it only matches full words!

🎉  magic to me hahaha

**Comment by melissarudofsky** [comment]
oh wait, I'm wrong - I don't know haha

**Comment by jestapinski** [comment]
Got the go-ahead, thanks Melissa!

**Pull request merged**
