### PR TITLE
Add npm test GH action

### PR DESCRIPTION
**Pull request by jestapinski**
This PR adds a simple action to run `npm test` on a PR to staging or master

### CODE REVIEW

**Comment by greggb** [comment]
Do the actions cache at all?

**Comment by jestapinski** [comment]
> Do the actions cache at all?

[We can cache dependencies](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows) so those don't run each time. Should be pretty easy to add in here. Anything else we would want to cache?

**Comment by greggb** [comment]
> > Do the actions cache at all?
> 
> [We can cache dependencies](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows) so those don't run each time. Should be pretty easy to add in here. Anything else we would want to cache?

Nothing that comes to mind

**Comment by jestapinski** [comment]
Looks like we are hitting the cache and cut build times by ~10s, so seems to be working as expected for caching downloaded deps.

Screen Shot 2020-03-27 at 3 10 20 PM

**Comment by greggb** [comment]
Where do you think the 37s are being spent in the `ci` task even with the cache?

**Comment by jestapinski** [comment]
> Where do you think the 37s are being spent in the `ci` task even with the cache?

Yeah this seems a bit off, it looks like it is trying to install deps still but maybe not download. From the docs:

```
Jobs on GitHub-hosted runners start in a clean virtual environment and must download dependencies each time, causing increased network utilization, longer runtime, and increased cost. To help speed up the time it takes to recreate these files, GitHub can cache dependencies you frequently use in workflows.
```

So even with deps cached, it looks like it is still installing each time.

**Comment by greggb** [comment]
Ha, that was the one, but looks like it does the same thing!

**Comment by jestapinski** [comment]
🤷‍♂ It seems a bit quicker than before? Down to 52s from 59s, so it is worth keeping for now.

**Comment by jestapinski** [comment]
Thanks!

**Pull request merged**
